config/routes.rb
Rails.application.routes.draw do

  get 'states/find_states_given_country_id'

  resources :admin  
  resources :categories
  resources :cities
  resources :countries
  resources :no_admin
  resources :states


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, :path => '', :path_names => 
  {:sign_in => 'login', :sign_out => 'logout',  :sign_up => 'signup', :edit => 'profile'}
  resources :users
  root  "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	validates :name, :presence => {:message => "Usted ingresar un nombre"}
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :state
  has_one :country, :through => :state
  validates :name, :presence => {:message => "Usted ingresar un nombre"}
end

app/models/country.rb
class Country < ApplicationRecord
	has_many :states
	has_many :cities, through: :state
	validates :name, :presence => {:message => "Usted ingresar un nombre"}
end

app/models/state.rb
class State < ApplicationRecord
  belongs_to :country, :foreign_key => 'country_id'
  has_many :cities
  accepts_nested_attributes_for :cities
  validates :name, :presence => {:message => "Usted ingresar un nombre"}

     def self.search_for_country_id(id)
        where("country_id = ?",id)        
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :password, :presence => {:message => "Usted debe ingresar la contraseña"}, length: {minimum: 6, maximum: 50, :message => "La contraseña debe tener al menos caracteres"}
  validates :email, :presence => {:message => "Usted ingresar un email"}
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	def index
	end

	def show
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, except:  [:show, :index]
  before_action :set_category, except: [:index, :new]

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category
    else
      render 'new'
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path
  end

  def edit
  end

  def index
    @search = Category.ransack(params[:q])
    @categories = @search.result.page(params[:page]).per(20).order(:name)
  end
  
  def new
    @category = Category.new
  end

  def set_category
    @category = Category.find(params[:id])
  end

  def show
  end

  def update
    if @category.update(category_params)
        redirect_to @category
    else
        render 'edit' 
    end
  end

  protected
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
	before_action :authenticate_user!, except:  [:show, :index]
	before_action :set_city, except: [:index, :new, :create]

	def create
		@city = City.new(city_params)

		if @city.save
			redirect_to @city
		else
			render 'new'
		end
	end

	def destroy
		@city.destroy
		redirect_to cities_path
	end

	def edit
	end

	def index
		@search = City.ransack(params[:q])
		@cities = @search.result.page(params[:page]).per(20)
	end


	def new
		@city = City.new
	end

	def set_city
		@city = City.find(params[:id])
	end

	def show
	end

	def update
		if @city.update(city_params)
			redirect_to @city
		else
			render 'edit'
		end
	end

	protected
		def city_params
			params.require(:city).permit(:name, :state_id, :country_id)
		end

end

app/controllers/countries_controller.rb
 class CountriesController < ApplicationController
	before_action :authenticate_user!, except:  [:show, :index]
	before_action :set_country, except: [:index, :new]
 	
 	def create
 		@country = Country.new(country_params)

 		if @country.save
 			redirect_to @country
 		else
 			render 'new'
 		end
 	end

 	def destroy
 		@country.destroy	
 		redirect_to countries_path
 	end

 	def edit
 	end

 	def index
		@search = Country.ransack(params[:q])
		@countries = @search.result.page(params[:page]).per(20).order(:name)
 	end

 	def new
 		@country = Country.new
 	end

 	def set_country
		@country = Country.find(params[:id])
 	end

 	def show
 	end

 	def update
 		if @country.update(country_params)
 			redirect_to @country
 		else
 			render 'edit'
 		end
 	end



 	protected
 	def country_params
 		params.require(:country).permit(:name)
 	end
 end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		if signed_in?
			
		end
	end
end

app/controllers/no_admin_controller.rb
class NoAdminController < ApplicationController
	def index
	end

	def show
	end
end

app/controllers/states_controller.rb
 class StatesController < ApplicationController
	before_action :authenticate_user!, except:  [:show, :index]
	before_action :set_state, except: [:index, :new, :create, :find_states_given_country_id]

 	def create
 		@state = State.new(state_params)

 		if @state.save
 			redirect_to @state
 		else
 			render 'new'
 		end
 	end

 	def destroy
 		@state.destroy	
 		redirect_to states_path
 	end

 	def find_states_given_country_id
	   country_id = params[:country_id]#utilizes the url to extract country_id ".../find_states_given_country_id?country_id=1"
	   states = State.search_for_country_id(country_id).order(:name).as_json#query the model for the data and convert it to a hash using as_json
	   respond_to do |format|
	        format.json { 
	            render json: states
	        } 
	   end
	end

 	def edit
 	end

 	def index
		@search = State.ransack(params[:q])
		@states = @search.result.page(params[:page]).per(20).order(:name)
 	end

 	def new
 		@state = State.new
 	end

 	def set_state
 		@state = State.find(params[:id])
 	end

 	def show
 	end

 	def update
 		if @state.update(state_params)
 			redirect_to @state
 		else
 			render 'edit'
 		end
 	end



 	protected
 	def state_params
 		params.require(:state).permit(:name, :country_id)
 	end
 end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def javascript(*files)
		content_for(:head) { javascript_include_tag(*files) }
	end

	def stylesheet(*files)
		content_for(:head) { stylesheet_link_tag(*files) }
	end

	
	def sortable(column, title = nil)
		title ||= column.titleize
		css_class = column == sort_column ? "current #{sort_direction}" : nil
		direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
		link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
	end
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/javascripts_helper.rb
module JavascriptsHelper
end

app/helpers/no_admin_helper.rb
module NoAdminHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/categories/_form.html.erb
<%=form_for @category do |f|%>
<% if @category.errors.any? %>
<div id="error_explanation">
	<h2>
		<%= pluralize(@category.errors.count, "error") %> No se puede guardar la categoría:
	</h2>
	<ul>
		<% @category.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>
<div class="row">
	<div class="col-xs-4 col-sm-6">
		<div class="form-horizontal">
			<div class="form-group">
				<%= f.label 'Nombre', class: "col-sm-2 control-label" %>
				<div class="col-sm-10">
					<%= f.text_field :name, autofocus: true, class: "form-control", placeholder: 'Ingrese el nombre de la categoría' %>
				</div>
			</div>
			<div class="form-group">
				<div class="col-sm-offset-4 col-sm-10">
					<%= f.submit "Enviar", class: "btn btn-primary btn-lg"  %>
				</div>
			</div>
		</div>
	</div>
</div>

<% end %>

app/views/categories/edit.html.erb
<div class="row">
	<div class="col-xs-12 col-sm-6 col-md-8">
		<br>
		<h2>Editar categoría</h2> 
			<br>
		<%= render 'form'%>

		<div class="col-sm-offset-2 col-sm-10">
			<%= link_to 'Atrás', categories_path,  {:class=>"btn btn-link"} %> 
		</div>
	</div>
</div>

app/views/categories/index.html.erb
<div class="col-xs-7 col-sm-5">
	<br>
		<h2>Categorias</h2> <br>
		<table style="width: 100%;">
			<tr>
				<th>Nombre</th>
				<th colspan="2">Acciones</th>
			</tr>

			<% @categories.each do |category|%>
			<tr>
				<td><%=category.name %></td>
				<td><%= link_to raw('<span class="glyphicon glyphicon-eye-open fa-2x"></span>'), category_path(category) %></td>
				<td><%= link_to raw('<span class="glyphicon glyphicon-edit fa-2x"></span>'), edit_category_path(category) %></td>
				<td><%= link_to raw('<span class="glyphicon glyphicon-trash fa-2x"></span>'), category_path(category), method: :delete, data: { confirm: '¿Está seguro?'} %></td>
			</tr>
			<% end %>
		</table>
		<br><br>
		<%= link_to 'Nueva categoría', new_category_path, {:class=>"btn btn-info"} %>
		<p><%= paginate @categories %></p>

</div>

<div class="col-xs-5 col-sm-3" id='right_new_item'>
	<%= link_to 'Nueva categoría', new_category_path, {:class=>"btn btn-info"} %>
</div>

app/views/categories/new.html.erb
<div class="row">
	<div class="col-xs-12 col-sm-6 col-md-8">
		<br>
		<h2>Nueva categoría</h2> 
			<br>
		<%= render 'form'%>

		<div class="col-sm-offset-2 col-sm-10">
			<%= link_to 'Atrás', categories_path, {:class=>"btn btn-link"} %> 
		</div>
	</div>
</div>

app/views/categories/show.html.erb
<div class="col-xs-12 col-sm-6 col-md-8">
	<br>
	<h2>Ver categoría</h2> 
	<p>
		<strong>Nombre:</strong>
		<%= @category.name%>
	</p>
	<p>
		<%= link_to 'Atrás', categories_path , {:class=>"btn btn-link"}%> | <%= link_to 'Editar', edit_category_path(@category), {:class=>"btn btn-link"} %>
	</p>
</div>

app/views/cities/_form.html.erb
<%= form_for @city  do |f| %>
<% if @city.errors.any? %>
<div id="error_explanation">
	<h2>
		<%= pluralize(@city.errors.count, "error") %> No se puede guardar el estado:
	</h2>
	<ul>
		<% @city.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>
<div class="row">
	<div class="col-xs-4 col-sm-6">
		<div class="form-horizontal">
			<div class="form-group">
				<%= f.label 'País', class: "col-sm-2 control-label"  %>
				<div class="col-sm-10">
					<%= f.collection_select(:country, Country.order(:name), :id, :name, {include_blank: 'Seleccione un país'},  class: "form-control", id: 'country_list' ) %>
				</div>
			</div>
			<div class="form-group">
				<%= f.label 'Estado', class: "col-sm-2 control-label"  %>
				<div class="col-sm-10">
					<%= f.collection_select(:state_id, [], :id, :name, {prompt: "Seleccione el estado"},  class: "form-control" ) %>
				</div>
			</div>
			<div class="form-group">
				<%= f.label 'Nombre',  class: "col-sm-2 control-label" %>
				<div class="col-sm-10">
					<%= f.text_field :name, autofocus: true, class: "form-control", placeholder: 'Ingrese el nombre de la ciudad'  %>
				</div>
			</div>
			<div class="form-group">
				<div class="col-sm-offset-4 col-sm-10">
					<%= f.submit "Enviar", class: "btn btn-primary btn-lg"  %>
				</div>
			</div>
		</div>
	</div>
</div>
<% end %>

app/views/cities/_search.html.erb
<%= search_form_for @search do |f| %>	
	<div class="form-group">		
		<%= f.text_field :name_cont, autofocus: true, placeholder: 'Ingrese ciudad' %>
		<%= f.submit 'Buscar', class: "btn btn-link"  %>
	</div>
<% end %>

app/views/cities/edit.html.erb
<div class="row">
	<div class="col-xs-12 col-sm-6 col-md-8">
		<br>
		<h2>Editar ciudad</h2> 
		<br>
		<%= render 'form'%>

		<div class="col-sm-offset-2 col-sm-10">
			<%= link_to 'Atrás', cities_path, {:class=>"btn btn-link"} %> 
		</div>
	</div>
</div>

app/views/cities/index.html.erb
<div class="col-xs-7 col-sm-5">
	<br>
	<h2>Ciudades</h2> <br>
	<%= render 'search' %>
	<table style= "width: 100%;">
		<tr>
			<th>Nombre</th>
			<th>Estado</th>
			<th >País</th>
			<th colspan="2">Acciones</th>
		</tr>

		<% @cities.each do |city|%>
		<tr>
			<td><%= link_to city.name, city_path(city) %></td>
			<td><%=city.state.name %></td>
			<% @armar =  '/assets/flags/'+ city.state.country.name %>
			<td><%= image_tag(@armar)%>  <%= city.state.country.name %></td>
			<td><%= link_to raw('<span class="glyphicon glyphicon-eye-open fa-2x"></span>'), city_path(city) %></td>
			<td><%= link_to raw('<span class="glyphicon glyphicon-edit fa-2x"></span>'), edit_city_path(city) %></td>
			<td><%= link_to raw('<span class="glyphicon glyphicon-trash fa-2x"></span>'), city_path(city), method: :delete, data: { confirm: '¿Está seguro?'} %></td>
		</tr>
		<% end %>
	</table>
	<br><br>
	<%= link_to 'Nueva ciudad', new_city_path, {:class=>"btn btn-info"} %>
	<p><%= paginate @cities %></p>

	
</div>


<div class="col-xs-5 col-sm-3" id='right_new_item'>
	<%= link_to 'Nueva ciudad', new_city_path, {:class=>"btn btn-info"} %>
</div>

app/views/cities/new.html.erb
<% javascript 'dynamic_states' %>

<div class="row">
	<div class="col-xs-12 col-sm-6 col-md-8">
		<br>
		<h2>Nueva ciudad</h2> 
		<br>
		<%= render 'form'%>

		<div class="col-sm-offset-2 col-sm-10">
			<%= link_to 'Atrás', cities_path, {:class=>"btn btn-link"} %> 
		</div>
	</div>
</div>

app/views/cities/show.html.erb
<div class="col-xs-12 col-sm-6 col-md-8">
	<br>
	<h2>Ver ciudad</h2> 
	<p>
		<strong>Nombre:</strong>
		<%= @city.name%>
	</p>
	<p>
		<strong>Estado:</strong>
		<%= @city.state.name%>
	</p>
		<p>
	<strong>País:</strong>
		<%= @city.state.country.name%>
	</p>
	<p>
		<%= link_to 'Atrás', cities_path, {:class=>"btn btn-link"} %> | <%= link_to 'Editar', edit_city_path(@city), {:class=>"btn btn-link"} %>
	</p>
</div>

app/views/countries/_form.html.erb
<%=form_for @country do |f|%>
<% if @country.errors.any? %>
<div id="error_explanation">
	<h2>
		<%= pluralize(@country.errors.count, "error") %> No se puede guardar el país:
	</h2>
	<ul>
		<% @country.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>
<div class="row">
	<div class="col-xs-4 col-sm-6">
		<div class="form-horizontal">
			<div class="form-group">
				<%= f.label 'Nombre', class: "col-sm-2 control-label" %>
				<div class="col-sm-10">
					<%= f.text_field :name, autofocus: true, class: "form-control", placeholder: 'Ingrese el nombre del país' %>
				</div>
			</div>
			<div class="form-group">
				<div class="col-sm-offset-4 col-sm-10">
					<%= f.submit "Enviar", class: "btn btn-primary btn-lg"  %>
				</div>
			</div>
		</div>
	</div>
</div>

<% end %>

app/views/countries/_search.html.erb
<%= search_form_for @search do |f| %>	
	<div class="form-group">		
		<%= f.text_field :name_cont, autofocus: true, placeholder: 'Ingrese país' %>
		<%= f.submit 'Buscar', class: "btn btn-link"  %>
	</div>
<% end %>

app/views/countries/edit.html.erb
<div class="row">
	<div class="col-xs-12 col-sm-6 col-md-8">
		<br>
		<h2>Editar país</h2> 
			<br>
		<%= render 'form'%>

		<div class="col-sm-offset-2 col-sm-10">
			<%= link_to 'Atrás', countries_path,  {:class=>"btn btn-link"} %> 
		</div>
	</div>
</div>

app/views/countries/index.html.erb
<div class="col-xs-7 col-sm-5">
	<br>
		<h2>Países</h2> <br>
		<%= render 'search' %>
		
		<table style= "width: 100%;">
			<tr>
				<th>Nombre</th>
				<th colspan="2">Acciones</th>
			</tr>

			<% @countries.each do |country|%>
			<tr>
				<% @armar =  '/assets/flags/'+ country.name %>
				<td> <%= image_tag(@armar)%> <%= country.name %></td>
				<td><%= link_to raw('<span class="glyphicon glyphicon-eye-open fa-2x"></span>'), country_path(country) %></td>
				<td><%= link_to raw('<span class="glyphicon glyphicon-edit fa-2x"></span>'), edit_country_path(country) %></td>
				<td><%= link_to raw('<span class="glyphicon glyphicon-trash fa-2x"></span>'), country_path(country), method: :delete, data: { confirm: '¿Está seguro?'} %></td>
			</tr>
			<% end %>
		</table>
		<br><br>
		<%= link_to 'Nuevo país', new_country_path, {:class=>"btn btn-info"} %>
			<p><%= paginate @countries %></p>
</div>

<div class="col-xs-5 col-sm-3" id='right_new_item'>
	<%= link_to 'Nuevo país', new_country_path, {:class=>"btn btn-info"} %>
</div>

app/views/countries/new.html.erb
<div class="row">
	<div class="col-xs-12 col-sm-6 col-md-8">
		<br>
		<h2>Nuevo país</h2> 
			<br>
		<%= render 'form'%>

		<div class="col-sm-offset-2 col-sm-10">
			<%= link_to 'Atrás', countries_path, {:class=>"btn btn-link"} %> 
		</div>
	</div>
</div>

app/views/countries/show.html.erb
<div class="col-xs-12 col-sm-6 col-md-8">
	<br>
	<h2>Ver país</h2> 
	<p>
		<strong>Nombre:   </strong>
		<% @armar =  '/assets/flags/'+ @country.name %>
		<%=image_tag(@armar)%> <%=  @country.name %>
	</p>
	<p>
		<%= link_to 'Atrás', countries_path , {:class=>"btn btn-link"}%> | <%= link_to 'Editar', edit_country_path(@country), {:class=>"btn btn-link"} %>
	</p>
</div>

app/views/states/_form.html.erb
<%=form_for @state do |f|%>
<% if @state.errors.any? %>
<div id="error_explanation">
	<h2>
		<%= pluralize(@state.errors.count, "error") %> No se puede guardar el estado:
	</h2>
	<ul>
		<% @state.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>
<div class="row">
	<div class="col-xs-4 col-sm-6">
		<div class="form-horizontal">
			<div class="form-group">
				<%= f.label 'País', class: "col-sm-2 control-label"  %>
				<div class="col-sm-10">
					<%= f.collection_select :country_id, Country.order(:name), :id, :name, {prompt: "Seleccione el país"},  class: "form-control"  %>
				</div>
			</div>
			<div class="form-group">
				<%= f.label 'Nombre', class: "col-sm-2 control-label" %>
				<div class="col-sm-10">
					<%= f.text_field :name, autofocus: true, class: "form-control", placeholder: 'Ingrese el nombre del estado' %>
				</div>
			</div>
			<div class="form-group">
				<div class="col-sm-offset-4 col-sm-10">
					<%= f.submit "Enviar", class: "btn btn-primary btn-lg"  %>
				</div>
			</div>
		</div>
	</div>
</div>
<% end %>

app/views/states/_search.html.erb
<%= search_form_for @search do |f| %>	
	<div class="form-group">		
		<%= f.text_field :name_cont, autofocus: true, placeholder: 'Ingrese estado' %>
		<%= f.submit 'Buscar', class: "btn btn-link"  %>
	</div>
<% end %>

app/views/states/edit.html.erb
<div class="row">
	<div class="col-xs-12 col-sm-6 col-md-8">
		<br>
		<h2>Editar estado</h2> 
			<br>
		<%= render 'form'%>

		<div class="col-sm-offset-2 col-sm-10">
			<%= link_to 'Atrás', states_path, {:class=>"btn btn-link"} %> 
		</div>
	</div>
</div>

app/views/states/index.html.erb
<div class="col-xs-7 col-sm-5">
	<br>
		<h2>Estados</h2> <br>
		<%= render 'search' %>

		<table style= "width: 100%;">
			<tr>
				<th>Nombre</th>
				<th>País</th>
				<th colspan="2">Acciones</th>
			</tr>

			<% @states.each do |state|%>
			<tr>
				<% @armar =  '/assets/flags/'+ state.country.name %>
				<td><%=state.name %></td>
				<td style="white-space: nowrap" > <%= image_tag(@armar)%> <%= state.country.name %></td>
				<td><%= link_to raw('<span class="glyphicon glyphicon-eye-open fa-2x"></span>'), state_path(state) %></td>
				<td><%= link_to raw('<span class="glyphicon glyphicon-edit fa-2x"></span>'), edit_state_path(state) %></td>
				<td><%= link_to raw('<span class="glyphicon glyphicon-trash fa-2x"></span>'), state_path(state), method: :delete, data: { confirm: '¿Está seguro?'} %></td>
			</tr>
			<% end %>
		</table>
		<br><br>
		<%= link_to 'Nuevo estado', new_state_path, {:class=>"btn btn-info"} %>
		<p><%= paginate @states %></p>
	
</div>
<div class="col-xs-5 col-sm-3" id='right_new_item'>
	<%= link_to 'Nuevo estado', new_state_path, {:class=>"btn btn-info"} %>
</div>

app/views/states/new.html.erb
<div class="row">
	<%=render 'layouts/admin'%>
	<div class="col-xs-12 col-sm-6 col-md-8">
		<br>
		<h2>Nuevo estado</h2> 
			<br>
		<%= render 'form'%>

		<div class="col-sm-offset-2 col-sm-10">
			<%= link_to 'Atrás', states_path, {:class=>"btn btn-link"} %> 
		</div>
	</div>
</div>

app/views/states/show.html.erb
<div class="col-xs-12 col-sm-6 col-md-8">
	<br>
	<h2>Ver estado</h2> 
	<p>
		<strong>Nombre:</strong>
		<%= @state.name%>
	</p>
	<p>
		<%= link_to 'Atrás', states_path, {:class=>"btn btn-link"} %> | <%= link_to 'Editar', edit_state_path(@state), {:class=>"btn btn-link"} %>
	</p>
</div>