config/routes.rb
Rails.application.routes.draw do

  get 'states/find_states_given_country_id'

  resources :admin  
  resources :categories
  resources :cities
  resources :countries
  resources :no_admin
  resources :states


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, :path => '', :path_names => 
  {:sign_in => 'login', :sign_out => 'logout',  :sign_up => 'signup', :edit => 'profile'}
  resources :users
  root  "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	validates :name, :presence => {:message => "Usted ingresar un nombre"}
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :state
  has_one :country, :through => :state
  validates :name, :presence => {:message => "Usted ingresar un nombre"}
end

app/models/country.rb
class Country < ApplicationRecord
	has_many :states
	has_many :cities, through: :state
	validates :name, :presence => {:message => "Usted ingresar un nombre"}
end

app/models/state.rb
class State < ApplicationRecord
  belongs_to :country, :foreign_key => 'country_id'
  has_many :cities
  accepts_nested_attributes_for :cities
  validates :name, :presence => {:message => "Usted ingresar un nombre"}

     def self.search_for_country_id(id)
        where("country_id = ?",id)        
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :password, :presence => {:message => "Usted debe ingresar la contraseña"}, length: {minimum: 6, maximum: 50, :message => "La contraseña debe tener al menos caracteres"}
  validates :email, :presence => {:message => "Usted ingresar un email"}
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	def index
	end

	def show
	end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
	before_action :authenticate_user!, except:  [:show, :index]
	before_action :set_city, except: [:index, :new, :create]

	def create
		@city = City.new(city_params)

		if @city.save
			redirect_to @city
		else
			render 'new'
		end
	end

	def destroy
		@city.destroy
		redirect_to cities_path
	end

	def edit
	end

	def index
		@search = City.ransack(params[:q])
		@cities = @search.result.page(params[:page]).per(20)
	end


	def new
		@city = City.new
	end

	def set_city
		@city = City.find(params[:id])
	end

	def show
	end

	def update
		if @city.update(city_params)
			redirect_to @city
		else
			render 'edit'
		end
	end

	protected
		def city_params
			params.require(:city).permit(:name, :state_id, :country_id)
		end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		if signed_in?
			
		end
	end
end

app/controllers/no_admin_controller.rb
class NoAdminController < ApplicationController
	def index
	end

	def show
	end
end

app/controllers/states_controller.rb
 class StatesController < ApplicationController
	before_action :authenticate_user!, except:  [:show, :index]
	before_action :set_state, except: [:index, :new, :create, :find_states_given_country_id]

 	def create
 		@state = State.new(state_params)

 		if @state.save
 			redirect_to @state
 		else
 			render 'new'
 		end
 	end

 	def destroy
 		@state.destroy	
 		redirect_to states_path
 	end

 	def find_states_given_country_id
	   country_id = params[:country_id]#utilizes the url to extract country_id ".../find_states_given_country_id?country_id=1"
	   states = State.search_for_country_id(country_id).order(:name).as_json#query the model for the data and convert it to a hash using as_json
	   respond_to do |format|
	        format.json { 
	            render json: states
	        } 
	   end
	end

 	def edit
 	end

 	def index
		@search = State.ransack(params[:q])
		@states = @search.result.page(params[:page]).per(20).order(:name)
 	end

 	def new
 		@state = State.new
 	end

 	def set_state
 		@state = State.find(params[:id])
 	end

 	def show
 	end

 	def update
 		if @state.update(state_params)
 			redirect_to @state
 		else
 			render 'edit'
 		end
 	end



 	protected
 	def state_params
 		params.require(:state).permit(:name, :country_id)
 	end
 end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def javascript(*files)
		content_for(:head) { javascript_include_tag(*files) }
	end

	def stylesheet(*files)
		content_for(:head) { stylesheet_link_tag(*files) }
	end

	
	def sortable(column, title = nil)
		title ||= column.titleize
		css_class = column == sort_column ? "current #{sort_direction}" : nil
		direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
		link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
	end
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/javascripts_helper.rb
module JavascriptsHelper
end

app/helpers/no_admin_helper.rb
module NoAdminHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/layouts/_admin.html.erb
<br>
<br>
<br>
<div class="row">
	<div class="col-xs-6 col-sm-3">
		<ul class="nav nav-pills nav-stacked" >
			<li class="<%= 'active' if params[:controller] == 'categories' %>"> <%= link_to 'Categorias', categories_path %></li> 
			<li class="<%= 'active' if params[:controller] == 'countries' %>"> <%= link_to 'Paises', countries_path %></li>      
			<li class="<%= 'active' if params[:controller] == 'states' %>"> <%= link_to 'Estados', states_path %></li>    
			<li class="<%= 'active' if params[:controller] == 'cities' %>"> <%= link_to 'Ciudades', cities_path %></li> 
		</ul>
	</div>

	<!-- Small button group -->
	<!-- Single button -->

app/views/layouts/_no_admin.html.erb
class HomeController < ApplicationController
	def index
		if signed_in?
			if current_user.admin == true
      			redirect_to :controller => 'categories', :action => 'index' 
  			else
      			redirect_to :controller => 'no_admin', :action => 'index'
  			end
		end
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<% javascript 'bootstrap' %>
	<%= favicon_link_tag 'favicon.ico' %>
	<title>Directorio</title>
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	<%= yield(:head) %>
	<div class="row">
		<nav class="navbar navbar-default navbar-fixed-top">
			<div class="container">
				<div class="navbar-header">
					<a class="navbar-brand" href="http://localhost:3000/home"> <%= image_tag("small logo.png") %> </a>
				</div>
				<div class="collapse navbar-collapse" id="myNavbar">
					<% if user_signed_in? %>
					<ul class="nav navbar-nav navbar-right">
						<li><a href="profile"><span class="glyphicon glyphicon-user"></span> <%= current_user.email %></a></li>
						<li> <%= link_to raw('Cerrar sesión <span class="glyphicon glyphicon-off"></span>'), destroy_user_session_path, :method => :delete %></li>
					</ul>
					<% else %>
					<ul class="nav navbar-nav navbar-right" >
						<li><a href="signup">Registrarse</a></li>
						<li><a href="login" >Iniciar sesión</a></li>
					</ul>
					<% end %>
				</div>
			</div>
		</nav>
	</div>
</head>
<body>
	<% if user_signed_in? && current_user.active == true %>
		<% if current_user.privilege == 'admin'%>
			<%= render 'layouts/admin' %>
		<% else %>
			<%= render 'layouts/no_admin' %>
		<% end %>
	<% end %>
	<% if notice %>
		<p class="notice"><%= notice %></p>
	<% end %>
	<% if alert %>
			<p class="alert"><%= alert %></p>
	<% end %>
	<%= yield %>
</body>
</html>